language: node_js
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: www.aquienvotas.org
  region: sa-east-1
  skip_cleanup: true
  acl: public_read
  local_dir: build
  on:
    repo: andresmoritan/aquienvotas
    branch: master
